[package]
name = "compile"
version = "0.1.0"
edition = "2021"

[dependencies]
data_structs = { path = "../data_structs"}
unicode-segmentation = "1.12.0"
serde_json = "1.0"
serde = "1.0"
bincode = "2.0.1"
